// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[id].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/getAll/index.ts";
import * as $3 from "./routes/api/invitations/index.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/list.tsx";
import * as $6 from "./routes/spin.tsx";
import * as $$0 from "./islands/Invitations.tsx";
import * as $$1 from "./islands/list.tsx";

const manifest = {
  routes: {
    "./routes/[id].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/getAll/index.ts": $2,
    "./routes/api/invitations/index.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/list.tsx": $5,
    "./routes/spin.tsx": $6,
  },
  islands: {
    "./islands/Invitations.tsx": $$0,
    "./islands/list.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
